# Generated by Django 3.1.2 on 2020-10-24 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_map.city')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('house', models.IntegerField(verbose_name='дом')),
                ('opening_time', models.TimeField(verbose_name='время открытия')),
                ('closing_time', models.TimeField(verbose_name='время закрытия')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_map.city')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_map.street')),
            ],
        ),
    ]
