# Generated by Django 3.1.2 on 2020-11-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='open',
            field=models.BooleanField(default=0),
        ),
    ]
