# Generated by Django 3.1.2 on 2020-10-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_map', '0002_auto_20201024_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='open',
            field=models.BooleanField(default=1, null=True),
        ),
    ]
